#reference: http://www.appveyor.com/docs/appveyor-yml

version: 1.3.4.{build}

branches: 
  only:
   - master
  
os: Windows Server 2012
   
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true  
  
configuration: Release

build:
  project: SpriterDotNet.sln
  publish_nuget: true
  
before_build:
  nuget restore SpriterDotNet.sln

artifacts:
  - path: out\*.nupkg
